### ISSUE TITLE
Bug Report: On Press is not working for android device or emulator

### ISSUE THREAD

**Issue by zubairniazi94** [FaridSafi/react-native-google-places-autocomplete#788] opened 2021-12-09 08:58 UTC
# On Press is not working for android device or emulator

Hi,

On Press is not working for android device or emulator. I using it in modal but also tried in plain view or scrollview both. I have been looking for solution last couple of days. I went through some other devs also mentioned the similar problem. They purposed the solution might be enabling billing configurations, some said remove it from scrollview. I tried both, none worked for me. 

In IOS emulator it's working fine, onPress is also working. In android, search works but when pressing on item from search result, nothing happens and list disappears.

Any help will be appreciated. Thank You. :)

# Reproduction

<details>
  <summary>GPlace Component</summary>

  ```javascript
 <GooglePlacesAutocomplete
    placeholder="Search"
    query={{
      key: GOOGLE_PLACES_API_KEY,
      language: "en", // language of the results
    }}
    onPress={(data, details = null) => {
      console.log(data, details);

      setFieldValue(name, data.description);
      setModalVisible(false);
    }}
    onFail={(error) => console.error(error)}
    requestUrl={{
      url: "https://cors-anywhere.herokuapp.com/https://maps.googleapis.com/maps/api",
      useOnPlatform: "web",
    }} // this in only required for use on the web. See https://git.io/JflFv more for details.
  />
  ```
</details>

<details>
  <summary>Modal Component</summary>

  ```javascript
  <Modal visible={modalVisible} animationType="slide">
    <ScreenWithoutScroll
      style={{
        flex: 1,
        padding: 10,
        backgroundColor: defaultStyles.colors.light,
      }}
      >
    <Button title="Close" onPress={() => setModalVisible(false)} />
    
    <GPlace name={name} setModalVisible={setModalVisible} />
    </ScreenWithoutScroll>
  </Modal>
  ```
</details>

# Additional context

- Library Version: 2.4.1
- React Native Version: 0.64.3

- [x] iOS
- [x] Android
- [ ] Web
- [x] I am using expo

**Comment by nusjose** [comment] 2021-12-14 03:46
Any update?.

**Comment by mariomurrent-softwaresolutions** [comment] 2021-12-14 07:19
Same here - its not even working on my iOS Phone

**Comment by bobananto24** [comment] 2021-12-14 10:56
I am also facing the exact same issue as @zubairniaxi. Working fine in ios simulator but not in android

**Comment by bell-steven** [comment] 2021-12-14 15:58
I cannot reproduce this using Expo on an Android device. 
If someone provides a link to a snack or provide a more complete example I can try and take a look.

**Comment by zubairniaxi** [comment] 2021-12-24 15:45
Hi @bell-steven 

My apologies for late reply. Actually I got it working without scrollview. 

Let me explain:

I have a form in ScrollView component. In the form, I have a field that opens Modal which is not ScrollView. When I removed ScrollView from form component then it's working on android too. I guess it has some issue with ScrollView component. 

I have a huge form component that will not fit into screen so I have to add ScrollView component. I'm sharing expo link so you can get the idea.

Link: https://expo.dev/@zubairniazi/ScheduleApp

Thanks a lot

**Comment by da794** [comment] 2022-02-09 23:10
estou enfrentando esse mesmo problema

**Comment by Asgaroth** [comment] 2022-02-11 22:52
Can confirm, it was working for me on the iOS simulator but not on the device. Fixed by removing the `ScrollView`

**Comment by buneme** [comment] 2022-02-12 20:28
Adding `keyboardShouldPersistTaps={"always"}` worked for me

**Comment by zubairniazi94** [comment] 2022-02-16 06:48
> I had this issue when using the component in a scrollview - adding `keyboardShouldPersistTaps={"always"}` to the scrollview fixed it for me.

It resolved the issue. Thanks a lot @buneme

**Closed** 2022-02-16 06:53 UTC
Labels: bug, awaiting author response
