### ISSUE TITLE
react-native-google-places-autocomplete not working on React native 0.61

### ISSUE THREAD

**Issue by ahmadali9289** [FaridSafi/react-native-google-places-autocomplete#503] opened 2020-02-12 11:35 UTC
Hi,

I have added react-native-google-places-autocomplete with yarn in my react-native cli project but it is not working. Here are the issues I am facing at the moment.
 
1. the places drop down is not showing up on IOS, however the input text field allows me to enter a place name but the predictions list does not appear

2. onPress handler is not triggered at all on both IOS and android

3. The Text Input coming from react-native-google-places-autocomplete does not allow me to enter anything on ANDROID. It is like disabled all the time ( although the focus is set to true)

Note: all google location apis are enabled , google maps api, places api and geocode api are enabled and a valid api key is given.

I tried all possible solutions available including the following:

1. setting zIndex: 1000 a high value to avoid it being hidden behind some other view 

2. Tried creating new RN App and added only this component to keep the project clean 
3. Regenerating the API and even using another api which works with previous versions of REACT NATIVE. 

The logs don't show anything on both Xcode and Android Studio. Here is the code snippet:
```
                 <View style = {[{zIndex: 2, backgroundColor: 'white'}]}>
				<GooglePlacesAutocomplete
					ref = {ref => setSearchTextRef(ref)}
					placeholder='Search for gym'
					styles={{
						container: {backgroundColor: 'transparent'},
						textInputContainer: styles.viewStyle,
						textInput: styles.textInputStyle,
					}}
					keyboardShouldPersistTaps = {'handled'}
					listUnderlayColor = {'transparent'}
					textInputProps = {{
						onFocus: () => focusInput(),
						onBlur: () => blurInput(),
						onChangeText: (text) => onChange(text)
					}}
					minLength={1} // minimum length of text to search
					returnKeyType={'search'}
					listViewDisplayed={'auto'}   // true/false/undefined
					fetchDetails={true}
					renderDescription={row => row.description} // custom description render
					onPress={(data, details = null) => {
						let coordinates = details.geometry.location;
						sendCoordinates(coordinates, {data, details});
					}}
					getDefaultValue={() => ''}
					query={{
						key: googleAPIKey,
						language: 'en', // language of the results
						// types: '(cities)' // default: 'geocode'
					}}
					nearbyPlacesAPI='GooglePlacesSearch' // Which API to use: GoogleReverseGeocoding or GooglePlacesSearch
					GooglePlacesSearchQuery={{
						rankby: 'distance',
						types: 'gym'
					}}
					filterReverseGeocodingByTypes={['locality', 'administrative_area_level_3']} 
					debounce={200}
				/>
			</View>

```

Thank you in advance

**Comment by vrgimael** [comment] 2020-02-13 23:58
I'm observing the same issue but only in some scenes in my app - I'm not 100% sure that's the cause but I suspect it won't work because it's inside a modal component. It works fine somewhere else in the app though.

Any thoughts?

**Comment by vrgimael** [comment] 2020-02-14 00:06
Actually just solved it by following the steps [here](https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/478#issuecomment-573344080)

**Comment by josepaulodelacruz** [comment] 2020-02-21 07:55
Im having this kind of problem to. unable to fetch search places

**Comment by jaing** [comment] 2020-03-06 14:23
This package is no longer maintained and simply not working. I tried on IOS with expo. I didn't even get a list of results. I found a other package that is working like a charm:

https://www.npmjs.com/package/react-native-places-input

**Comment by devfilsk** [comment] 2020-04-10 16:16
Hi guys. 
I was having the same issue with this lib, and after try for some hours, i find a solution. 
The problem was in the billing configuration on google APIs. 
Try configure the project what you are using key for and active billings configurations, it solved my problem. try it and tell me if it works.

Obs. I'm sorry about the poor english, but I hope this can help you.

**Comment by bfraiman** [comment] 2020-05-06 01:20
Any solution?

**Comment by bell-steven** [comment] 2020-05-19 14:27
@ahmadali9289 using the code you provided, this works as expected for me. 

> ```
>textInputProps = {{
>     onFocus: () => focusInput(),
>	onBlur: () => blurInput(),
>	onChangeText: (text) => onChange(text)
>}}```

You didn't indicate what these functions do, this could be the problem. 
Another likely cause is that your component is wrapped within a `ScrollView`.

**Comment by bell-steven** [comment] 2020-05-22 14:44
I can't reproduce this, so i'm going to close this. If you encounter this, and this is still a problem for you, please open a new issue (please follow the issue template).

**Closed by bell-steven** 2020-05-22 14:44 UTC
Labels: awaiting author response

**Comment by itsGabriel** [comment] 2020-06-16 17:26
i'm facing the same problem, but only happens with IOS. I cant click in none of listview items(except if i click randomly several times over they)

**Comment by sujatha2016** [comment] 2020-11-01 07:00
Am not sure if anybody else had/have this issue.. I too got this error on searching I saw _onFail_ is available. ` onFail={error => console.log('error' + error)}` this will give you error. If suppose the error is something like _This IP, site or mobile application is not authorized to use this API key. Request received from IP address $someipaddress, with empty referer_. Then do create a SERVER KEY instead of normal api key. Creating a server key is same like creating api key. Under the heading **Application Restrictions** select IP addresses instead of none. thus you are good. This was my trouble. Hope no one else will be stuck around this. Also make sure billing is enabled for your project.

![Screenshot 2020-11-01 at 12 28 50 PM](https://user-images.githubusercontent.com/22787816/97796920-ce9e5d80-1c3d-11eb-812c-7b3cc44e54f8.png)

Hope this helps someone

**Comment by Prakhar-64** [comment] 2021-08-13 13:35
I'm not getting any list. any solution?

**Comment by Inzicoder** [comment] 2021-08-18 12:16
same issue here got stuck on this for more than 5 hours.

**Comment by da45** [comment] 2022-02-17 20:02
> same issue here got stuck on this for more than 5 hours.

Hi , did you find any fix?

**Comment by mharrisweb** [comment] 2022-04-11 14:18
Same issue, I've yet to find an google address autocomplete component that actually works.

**Comment by naor572** [comment] 2022-09-15 05:15
can't see the autocomplete of google places someone knows why? I wrapped the component with a view and add the style of height: "100%" and it's not the problem...

**Comment by Etienne971** [comment] 2022-11-11 12:19
If I can still help someone, here is what I did to fix the not showing list issue : 

`container: {
       flex: 0,
  },`

Applied to styles of <GooglePlacesAutocomplete>

**Comment by dansalomon2015** [comment] 2022-11-20 18:50
> I'm observing the same issue but only in some scenes in my app - I'm not 100% sure that's the cause but I suspect it won't work because it's inside a modal component. It works fine somewhere else in the app though.
> 
> Any thoughts?

You were right. I faced the same issue with a modal. I removed it and used a view with position "absolute"

**Comment by DimKrz** [comment] 2023-01-21 18:31
Hello everyone,
I had the same problem. My code format was this: 

After all the solutions i tried nothing was working. Even though I had everything completed even the billing configuration on the google APIs, the the places drop down just wasn't showing. 

So at start I reinstalled GooglePlacesAutocomplete with "yarn add react-native-google-places-autocomplete", if you have npm do the "npm i react-native-google-places-autocomplete".

Then I added these two imports again from the start:

import { GooglePlacesAutocomplete } from "react-native-google-places-autocomplete";
import { GOOGLE_MAPS_APIKEY } from "@env";

Then  I  rewrote GooglePlacesAutocomplete & GOOGLE_MAPS_APIKEY in my code:

<GooglePlacesAutocomplete
          placeholder="Where From?"
          styles={{
            container: {
              flex: 0,
            },
            textInput: {
              fontSize: 18,
            },
          }}
          query={{
            key: GOOGLE_MAPS_APIKEY,
            language: "en",
          }}
          nearbyPlacesAPI="GooglePlacesSearch"
          debounce={200}
        />

so they define the "new imports" and do the command "yarn install" on my project file even though it was already up to date.

Lastly, I restart my project with clean cache using the command "expo r -c".
Magically, it worked!

Hope, that helps someone in the future!

**Comment by returnvoid** [comment] 2023-03-22 18:45
> If I can still help someone, here is what I did to fix the not showing list issue :
> 
> `container: { flex: 0, },`
> 
> Applied to styles of `<GooglePlacesAutocomplet />`

This worked for me. For people who thought this could be related to enable billing, first check something like this to see if the api is returning data:

`renderRow={(rowData) => {
                const title = rowData.structured_formatting.main_text;
                const address = rowData.structured_formatting.secondary_text;
                console.log('title & address:', title, address);
                return (
                    <View>
                        <Text style={{ fontSize: 14 }}>{title}</Text>
                        <Text style={{ fontSize: 14 }}>{address}</Text>
                    </View>
                );
            }}`

**Comment by nessmahm** [comment] 2024-01-17 19:36
this worked for me :

  <GooglePlacesAutocomplete
                placeholder="Search"
                minLength={2} // minimum length of text to search
                fetchDetails={true}
                onPress={(data, details = null) => {
                    // 'details' is provided when fetchDetails = true
                    console.log(data);
                    console.log(details);
                }}
                query={{
                    // available options: https://developers.google.com/places/web-service/autocomplete
                    key: apiKey,
                    language: 'en', // language of the results
                }}
                styles={{
                    description: {
                        fontWeight: 'bold',
                    },
                    predefinedPlacesDescription: {
                        color: '#1faadb',
                    },
                    listView: {
                        color: 'black', //To see where exactly the list is
                        zIndex: 1000, //To popover the component outwards
                        position: 'absolute',
                        top: 45
                    },
                }}
                currentLocation={true} // Will add a 'Current location' button at the top of the predefined places list
                currentLocationLabel="Current location"
                nearbyPlacesAPI="GooglePlacesSearch" // Which API to use: GoogleReverseGeocoding or GooglePlacesSearch
                GoogleReverseGeocodingQuery={
                    {
                        // available options for GoogleReverseGeocoding API : https://developers.google.com/maps/documentation/geocoding/intro
                    }
                }
                GooglePlacesDetailsQuery={{
                    // available options for GooglePlacesDetails API : https://developers.google.com/places/web-service/details
                    fields: 'formatted_address',
                }}
                filterReverseGeocodingByTypes={[
                    'locality',
                    'administrative_area_level_3',
                ]} // filter the reverse geocoding results by types - ['locality', 'administrative_area_level_3'] if you want to display only cities
            />

**Comment by flags-brighton** [comment] 2025-02-03 11:30
> [@ahmadali9289](https://github.com/ahmadali9289) using the code you provided, this works as expected for me.
> 
> > ```
> > textInputProps = {{
> >     onFocus: () => focusInput(),
> >   onBlur: () => blurInput(),
> >   onChangeText: (text) => onChange(text)
> > }}```
> > ```
> 
> You didn't indicate what these functions do, this could be the problem. Another likely cause is that your component is wrapped within a `ScrollView`.





https://stackdev.space/questions/searching-for-places-on-ios-using-the-google-place-search-api
