### ISSUE TITLE
VirtualizedLists should never be nested inside plain ScrollViews with the same orientation - use another VirtualizedList-backed container instead.

### ISSUE THREAD

**Issue by archana-iron** [FaridSafi/react-native-google-places-autocomplete#475] opened 2019-11-28 04:20 UTC
After upgrading to react-native 0.61 I get a lot of warnings like that:

> VirtualizedLists should never be nested inside plain ScrollViews with the same orientation - use another VirtualizedList-backed container instead.

What is the other VirtualizedList-backed container that i should use, and why is it now advised not to use like that?

It comes when I am clicking on autocomplete.

**Comment by archana-iron** [comment] 2019-11-29 04:56
Any Solution??

**Comment by Rhomennik** [comment] 2019-12-02 20:50
ONly problem :(

**Comment by vendeesh** [comment] 2020-01-06 07:25
I have faced sam issues. Have any one got solution?

**Comment by archana-iron** [comment] 2020-01-06 08:24
> I have faced same issues. Have any one got solution?

Not yet :(

**Comment by natanaeladit** [comment] 2020-01-13 12:55
temporary solution

`import {YellowBox} from 'react-native';`

`YellowBox.ignoreWarnings([
      'VirtualizedLists should never be nested', // TODO: Remove when fixed
    ]);`

**Comment by CharlotteRdn** [comment] 2020-01-20 10:21
I face the same issue, did you resolve this ?

**Comment by mayupat13** [comment] 2020-01-23 11:43
I too have same issue. Any solution?

**Comment by kopax** [comment] 2020-02-08 09:15
I have a ScrolView within a ListView and I get this error.

**Comment by sharma-archu** [comment] 2020-02-10 03:05
> I too have same issue. Any solution?

not yet.

**Comment by yuritoledo** [comment] 2020-02-10 14:17
+ 1

**Comment by ranggabadrus** [comment] 2020-02-17 12:13
any update?

**Comment by forster007** [comment] 2020-02-19 14:30
Any update?

**Comment by YahiaBadr** [comment] 2020-04-08 04:17
any updates?

**Comment by rajnishcoder** [comment] 2020-04-27 12:49
any update?

**Comment by arjun-ravi** [comment] 2020-04-30 13:54
Any update?

**Comment by bell-steven** [comment] 2020-05-10 03:22
Can someone please provide a fully reproducible example of this by showing some code or better yet, linking to a [snack](https://snack.expo.io)?  I cannot reproduce this.

**Comment by bell-steven** [comment] 2020-05-12 19:17
Closing, as I can't reproduce this. Please open a new issue (with code reproduction or steps) if you encounter this.

**Closed by bell-steven** 2020-05-12 19:17 UTC
Labels: No reproduction, awaiting author response

**Comment by Hervera** [comment] 2020-11-15 10:06
This happens when there is a ScrollView as a parent element

**Comment by omarsoufiane** [comment] 2021-01-30 06:41
i guess this happens to everyone using nativebase theme copntainers. list do not display whenever there is an error in api call

**Comment by AmityTek** [comment] 2021-01-30 12:31
1 year after ... this issue is not fix really ??

**Comment by KrisLau** [comment] 2021-09-09 20:30
@bell-steven I can't reproduce this in a snack but it happens on my bare react native projects

**Comment by huzaifaaak** [comment] 2021-09-17 15:17
Also happening when using KeyboardAwareScrollView

**Comment by shmkane** [comment] 2021-09-27 22:47
Also having this issue.

**Comment by rubydeve** [comment] 2021-09-29 16:06
```
<ScrollView horizontal={false} style={{flex: 1, width: '100%', height: '100%'}}>
      <ScrollView horizontal={true} style={{flex: 1, width: '100%', height: '100%'}}>
            <GooglePlacesAutocomplete ... />
      </ScrollView>
</ScrollView>
``` 
use horizontal true false . Works 

- [ ]

**Comment by StevenL98** [comment] 2021-10-05 11:51
> ```
> <ScrollView horizontal={false} style={{flex: 1, width: '100%', height: '100%'}}>
>       <ScrollView horizontal={true} style={{flex: 1, width: '100%', height: '100%'}}>
>             <GooglePlacesAutocomplete ... />
>       </ScrollView>
> </ScrollView>
> ```
> 
> use horizontal true false . Works

This works! But now my styling is messed up, with the default styling the textinput will only stretch to full width if I start typing, do you know how I can fix it such that the textInput is always full width?

**Comment by rubydeve** [comment] 2021-10-05 19:47
> > ```
> > <ScrollView horizontal={false} style={{flex: 1, width: '100%', height: '100%'}}>
> >       <ScrollView horizontal={true} style={{flex: 1, width: '100%', height: '100%'}}>
> >             <GooglePlacesAutocomplete ... />
> >       </ScrollView>
> > </ScrollView>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > use horizontal true false . Works
> 
> This works! But now my styling is messed up, with the default styling the textinput will only stretch to full width if I start typing, do you know how I can fix it such that the textInput is always full width?

<ScrollView horizontal={false} style={{flex: 1, width: '100%', height: '100%'}}>
      <ScrollView horizontal={true} style={{flex: 1, width: '100%', height: '100%'}}>
            <GooglePlacesAutocomplete  
                          styles={{
			                container: {
					              width: '100%',
			              },
			              textInputContainer: {
				                    width: '100%',
				      },
			             textInput: {
			  	                   width: '100%',
			             }
                         }}
             />
      </ScrollView>
</ScrollView>

**Comment by marquina-abreu** [comment] 2021-11-20 02:34
![Screen Shot 2021-11-19 at 10 30 05 PM](https://user-images.githubusercontent.com/34238806/142711447-ca6d040e-4b4f-4cc0-b7bf-96642121b726.png)

```<Content
       horizontal={false}
       contentContainerStyle={styleContent}
       keyboardShouldPersistTaps="handled"
        showsVerticalScrollIndicator={false}>

      <ScrollView horizontal={true} contentContainerStyle={{flex: 1, width: '100%', height: '100%'}}>
           <GooglePlacesAutocomplete /> ......
       </ScrollView>
```

This is how it worked for me

**Comment by Abusayid693** [comment] 2022-02-11 11:23
> ```
> <ScrollView horizontal={false} style={{flex: 1, width: '100%', height: '100%'}}>
>       <ScrollView horizontal={true} style={{flex: 1, width: '100%', height: '100%'}}>
>             <GooglePlacesAutocomplete ... />
>       </ScrollView>
> </ScrollView>
> ```
> 
> 
>      
>   
> 
> use horizontal true false . Works

This works fine for me
