### ISSUE TITLE
Autocomplete does not work 

### ISSUE THREAD

**Issue by andymurakami** [FaridSafi/react-native-google-places-autocomplete#510] opened 2020-03-02 21:53 UTC
My component Search

```
import React, { Component } from 'react';
import { GooglePlacesAutocomplete } from 'react-native-google-places-autocomplete';
import { Dimensions } from 'react-native';


export default class Search extends Component {
  render() {
    return <GooglePlacesAutocomplete

    keyboardShouldPersistTaps='always' 

    placeholder="Para Onde ?"
    placeholderTextColor="#333"
    minLength={2} // minimum length of text to search
    
    onPress={(data, details = null) => { // 'details' is provided when fetchDetails = true

    console.log('pressinou');
    console.log(data, details);
  }}
    query={{
        key: 'MY-API-KEY',
        language:'pt',
        
    }}

    nearbyPlacesAPI='GooglePlacesSearch'

    textInputProps={{
        autoCapitalize:"none",
        autoCorrect:false,
    }}
    fetchDetails={true}
   //enabledPoweredByContainer={false}
    
    styles={{
        container: {
          position: "absolute",
          top: Platform.select({ ios: 60, android: 40 }),
          width: "100%"
        },
        textInputContainer: {
          flex: 1,
          backgroundColor: "transparent",
          height: 54,
          marginHorizontal: 20,
          borderTopWidth: 0,
          borderBottomWidth: 0
        },
        textInput: {
          height: 54,
          margin: 0,
          borderRadius: 0,
          paddingTop: 0,
          paddingBottom: 0,
          paddingLeft: 20,
          paddingRight: 20,
          marginTop: 0,
          marginLeft: 0,
          marginRight: 0,
          elevation: 5,
          shadowColor: "#000",
          shadowOpacity: 0.1,
          shadowOffset: { x: 0, y: 0 },
          shadowRadius: 15,
          borderWidth: 1,
          borderColor: "#ddd",
          fontSize: 18
        },
        listView: {
          borderWidth: 1,
          borderColor: "#ddd",
          backgroundColor: "#fff",
          marginHorizontal: 20,
          elevation: 5,
          shadowColor: "#000",
          shadowOpacity: 0.1,
          shadowOffset: { x: 0, y: 0 },
          shadowRadius: 15,
          marginTop: 10
        },
        description: {
          fontSize: 16
        },
        row: {
          padding: 20,
          height: 58
        }
      }}



    >

    </GooglePlacesAutocomplete>;
  }
}
```
And my index.js
```
import React, { Component } from 'react';
import MapView from 'react-native-maps';
import Geolocation from '@react-native-community/geolocation';  // instalar por causa da nova versao do REACT-NATIVE
import { View } from 'react-native';
import Search from '../Search';

// import { Container } from './styles';


// yarn add react-native-google-places-autocomplete

export default class Map extends Component {

    state = {
        region: null,
    }

    async componentDidMount() {
        
        Geolocation.getCurrentPosition(
            ({ 
                coords: { latitude, longitude } 
            }) => {
               // console.log('latitude', latitude);
                this.setState({

                    region: {
                        latitude,
                        longitude,
                        latitudeDelta: 0.0143,
                        longitudeDelta: 0.0134
                    }
                })
               // alert('pegou');
            }, // sucesso 
            () => { alert(' erro ')}, // erro
            {
                timeout: 2000,
                enableHighAccuracy: true,
                maximumAge: 10000,
            }
        )
    }


    render() {
        const { region } = this.state;
        console.log('REGIAO', region);
        return (
            <View style={{ flex: 1 }}  >
                <MapView
                    style={{ flex: 1 }}
                    region={ region }
                    showsUserLocation
                    loadingEnabled

                ></MapView>
                <Search>

                </Search>
            </View>
        );
    }
}
```
After put 2 or 3 digits of address, nothing happens

**Comment by jaing** [comment] 2020-03-06 14:23
This package is no longer maintained and simply not working. I tried on IOS with expo. I didn't even get a list of results. I found a other package that is working like a charm:

https://www.npmjs.com/package/react-native-places-input

**Comment by bell-steven** [comment] 2020-05-19 14:16
@andymurakami I just ran your component file with no issues (See [this](https://snack.expo.io/@sbell/disrespectful-waffles) snack).

I did not use the index.js that you provided, as `react-native-maps` and `@react-native-community/geolocation` are not supported in expo. 

My guess is that your problem lies in your index.js file. Try adding `style={{ flex: 1 }}` to the `Search` component.

If you provide a full minimal reproduction I will be happy to take a look.

**Comment by bell-steven** [comment] 2020-05-22 14:45
I can't reproduce this, so i'm going to close this. If you encounter this, and this is still a problem for you, please open a new issue (please follow the issue template).

**Closed by bell-steven** 2020-05-22 14:45 UTC

**Comment by walterdl** [comment] 2021-02-09 18:10
@andymurakami did you solved it?

**Comment by andymurakami** [comment] 2021-02-09 18:35
Yes I solved re-install the components and use the flex:1.

Verify the key too, sometimes is only the wrong key.

RGDS








Em ter., 9 de fev. de 2021 às 15:11, Walter Devia <notifications@github.com>
escreveu:
