### ISSUE TITLE
Error: Request has not been opened

### ISSUE THREAD

**Issue by Willham12** [FaridSafi/react-native-google-places-autocomplete#910] opened 2023-09-28 07:10 UTC
v2.5.3

See https://github.com/FaridSafi/react-native-google-places-autocomplete/blob/master/GooglePlacesAutocomplete.js#L559

**Comment by flogoerlich** [comment] 2023-09-29 09:40
![image](https://github.com/FaridSafi/react-native-google-places-autocomplete/assets/139104469/ee9344a0-d930-4638-aaeb-5494ee88dd2e)

Same error here

**Comment by ArturoTorresMartinez** [comment] 2023-10-03 18:15
Same issue

**Comment by BrayhanV** [comment] 2023-10-04 15:15
Same problem

**Comment by PrasanthDante03** [comment] 2023-10-05 12:05
any solution

**Comment by Felipelpk** [comment] 2023-10-09 15:38
same problem here

**Comment by athaljen** [comment] 2023-10-27 11:15
i fixed it by removing the line that throw Error.

Go to react-native>Libraries>Network>XMLHttpRequest.js    Line 517

-   throw new Error('Request has not been opened');
+  console.warn('Request has not been opened');

then patch-package react-native
that's all

**Comment by Najeeb-Idrees** [comment] 2023-12-04 16:09
@FaridSafi : Any update? When this will be fixed inside the package?

**Comment by jeffreyvalle** [comment] 2023-12-19 20:26
Update on this? Experiencing the same issue, is the solution really to remove the error logic itself?

**Comment by nppull** [comment] 2023-12-20 09:29
My solution
I am not use lib, I use url from google

`https://maps.googleapis.com/maps/api/place/autocomplete/json
  ?input=Vict
  &language=fr
  &types=geocode
  &key=YOUR_API_KEY`

**Comment by jeffreyvalle** [comment] 2023-12-20 18:33
> i fixed it by removing the line that throw Error.
> 
> Go to react-native>Libraries>Network>XMLHttpRequest.js Line 517
> 
> - throw new Error('Request has not been opened'); + console.warn('Request has not been opened');
> 
> then patch-package react-native that's all

I recommend instead modifying GooglePlacesAutocomplete.js, right before ```request.send()``` on line 570 add an if-gate to catch any unopened requests before calling request.send(). The error is being caused by request.send() being called on a request that is not yet opened. You can check for this case and only send if the request is opened, or readyState === 1, with:

```
if (request.readyState === 1) {
        request.send();
} else {
        console.warn('google places autocomplete: attempt to send unopened request failed');
}
```

This way you at least don't have to alter the logic for all XMLHttpRequest(which I am personally uncomfortable with), just the offending GooglePlacesAutocomplete logic.

I did not spend time looking into why/how a single request is failing to set readyState = 1. Someone else may dig into that and solve the overall issue. On my end, only 1 request fails to set readyState = 1, causing the 'Request has not been opened'. This only occurs after the user navigates away from the screen that contains the GooglePlacesAutocomplete component/import. 

Go ahead and add a console log right before line 570 in GooglePlacesAutocomplete and see what you get, make sure to log out any request where request.readyState !== 1 so you catch any requests that aren't open when they should be.

Hope this helps, happy coding.

**Comment by bjarheim** [comment] 2024-01-18 12:25
Setting debounce to more than 0 (eg. debounce={300}) fixed the issue for me.

**Comment by biswajeet728** [comment] 2024-02-22 15:11
> Setting debounce to more than 0 (eg. debounce={300}) fixed the issue for me.

Can you explain where to set debounce please !

**Comment by manibharathyr** [comment] 2024-02-23 06:57
> > Setting debounce to more than 0 (eg. debounce={300}) fixed the issue for me.
> 
> Can you explain where to set debounce please !


You can put the prop in GooglePlacesAutocomplete

<GooglePlacesAutocomplete 
 debounce={300}
/>

But it doesn't work, still throws an error.

**Comment by karan-sps** [comment] 2024-03-13 05:23
wrapping [ request.send(); ] everywhere with try catch block solved my crash in release.

**Comment by Hassaan0** [comment] 2024-06-24 08:09
> Setting debounce to more than 0 (eg. debounce={300}) fixed the issue for me.

Thank you, the issue has been resolved for me. However, I'm curious as to why this problem occurred. I've been using 'react-native-google-places-autocomplete' for the past 6-7 months without any issues, and now it suddenly appeared. Could you provide some insight into why this might have happened?

**Closed** 2024-08-02 09:29 UTC
Labels: bug

**Comment by Pranabemed** [comment] 2024-10-30 10:24
@manibharathyr  @biswajeet728 
This issue has been resolved ,please check once & do change properly 
====>>>GooglePlacesAutocomplete.defaultProps = {
  autoFillOnNotFound: false,
  currentLocation: false,
  currentLocationLabel: 'Current location',
  debounce: 300,   //here change required 0 => 300 (Please do it & working fine)
  disableScroll: false,
  enableHighAccuracyLocation: true,
  enablePoweredByContainer: true,
  fetchDetails: false,
  filterReverseGeocodingByTypes: [],
  GooglePlacesDetailsQuery: {},
  GooglePlacesSearchQuery: {
    rankby: 'distance',
    type: 'restaurant',
  },
  GoogleReverseGeocodingQuery: {},
  isRowScrollable: true,
  keyboardShouldPersistTaps: 'always',
  listHoverColor: '#ececec',
  listUnderlayColor: '#c8c7cc',
  listViewDisplayed: 'auto',
  keepResultsAfterBlur: false,
  minLength: 0,
  nearbyPlacesAPI: 'GooglePlacesSearch',
  numberOfLines: 1,
  onFail: () => {},
  onNotFound: () => {},
  onPress: () => {},
  onTimeout: () => console.warn('google places autocomplete: request timeout'),
  placeholder: '',
  predefinedPlaces: [],
  predefinedPlacesAlwaysVisible: false,
  query: {
    key: 'missing api key',
    language: 'en',
    types: 'geocode',
  },
  styles: {},
  suppressDefaultStyles: false,
  textInputHide: false,
  textInputProps: {},
  timeout: 20000,
  isNewPlacesAPI: false,
  fields: '*',
};

**Comment by melyux** [comment] 2024-11-03 07:35
I don't understand your comment @Pranabemed. So we no longer have to use `debounce={300}` to avoid this crash?

**Comment by Pranabemed** [comment] 2024-11-04 06:41
Yes avoid crash but you have to change in inside nodemodule then working

**Comment by dicarlomagnus** [comment] 2025-01-28 22:02
To me it worked perfectly, I just added it to the GooglePlacesAutocomplete
```

<GooglePlacesAutocomplete
  debounce={300} 
/>
```

That's it

I'm using the version:

"react-native-google-places-autocomplete": "2.5.6"
