### ISSUE TITLE
onChangeText is overlapping with other Input or TextInput Components

### ISSUE THREAD

**Issue by londri2go** [FaridSafi/react-native-google-places-autocomplete#508] opened 2020-02-23 07:14 UTC
```
`render(){
{
    return (
      <View>
        <Text  style={styles.header}>Pick Up Location</Text>
        <GooglePlacesAutocomplete
            styles={{  
              container: {
              position: "absolute",
              top: 40,
              width: "100%",
            },
            textInputContainer: {
              flex: 1,
              backgroundColor: "transparent",
              height: 54,
              marginHorizontal: 0,
              borderTopWidth: 0,
              borderBottomWidth: 0,
              paddingBottom: 50,
            },
            textInput: {
              height: 54,
              margin: 0,
              borderRadius: 0,
              paddingTop: 0,
              paddingBottom: 0,
              paddingLeft: 20,
              paddingRight: 20,
              marginTop: 0,
              marginLeft: 0,
              marginRight: 0,
              elevation: 5,
              shadowColor: "#000",
              shadowOpacity: 0.1,
              shadowOffset: { x: 0, y: 0 },
              shadowRadius: 15,
              borderWidth: 1,
              borderColor: "#ddd",
              fontSize: 18,
            },
            listView: {
              borderWidth: 1,
              borderColor: "#ddd",
              backgroundColor: "#fff",
              marginHorizontal: 20,
              elevation: 1,
              shadowColor: "#000",
              shadowOpacity: 0.1,
              shadowOffset: { x: 1, y: 0},
              shadowRadius: 15,
              marginTop: 10,
            },
            description: {
              fontSize: 16
            },
            row: {
              padding: 20,
              height: 58,
              backgroundColor: 'white'
            }}}
            keyboardShouldPersistTaps={"always"}
            placeholder="Where to pick up laundry?"
            placeholderTextColor="#333"
            returnKeyType={'default'}
            onPress={
              (data, details) => this.props.onLocationPress((data['description'], details))
              //(data, details) => { this.setState({addressEntered: data['description']})}
          }
            currentLocationLabel="Current location"
            currentLocation={false} // Will add a 'Current location' button at the top of the predefined places list
            query={{
              key: GOOGLE_MAPS_API_KEY,
              language: "en",
              components: 'country:pr'
            }}
            textInputProps={{
              autoCapitalize: "none",
              autoCorrect: false,
            }}
            fetchDetails={false}
            enablePoweredByContainer={true}
          />
          <Viewstyle= {styles.viewStyle}>
          <TextInput
              style={styles.containerStyle}
              defaultValue={this.props.numberOfHouse}
              onChangeText={(text) => this.props.onHousePress(text)}
              placeholder='#123-A'
          />
          </View>
          </View>
    );
  }
}

const styles = StyleSheet.create({
  viewStyle: {
    paddingTop: 200,
    zIndex: -1
  },
  containerStyle:{
    zIndex: -1 
  },
  container: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  header: {
    fontSize: hp('3.2%'),
    textAlign: 'center'
  },
});`
```

Every time I try to type into the input field, it will trigger  the autocomplete and erase whatever was written in the input field.

**Comment by bell-steven** [comment] 2020-05-20 14:00
Hi @londri2go I just tried the code you provided and I could not replicate the issue. 
Can you please provide a complete reproducible code example or a [snack](https://snack.expo.io)?

**Comment by bell-steven** [comment] 2020-05-22 14:44
I can't reproduce this, so i'm going to close this. If you encounter this, and this is still a problem for you, please open a new issue (please follow the issue template).

**Closed by bell-steven** 2020-05-22 14:44 UTC
