### ISSUE TITLE
Autocomplete Suggestions don't work with single tap

### ISSUE THREAD

**Issue by SandroBCIT** [FaridSafi/react-native-google-places-autocomplete#230] opened 2017-11-09 00:38 UTC
The autocomplete is working well, other than the fact that you have to double tap the search suggestions in order to interact with them. Is there a way to use a suggestion by just tapping once on them??

**Comment by RoysyLee** [comment] 2017-11-14 09:15
+1

**Comment by wbattel4607** [comment] 2017-12-06 01:06
Duplicate of #223

**Comment by lllymok** [comment] 2018-01-22 14:38
+1

**Comment by BryonApps** [comment] 2018-05-07 17:14
Make sure that any parent ScrollViews (or FlatList, etc.) of your GooglePlacesAutocomplete component have the prop `keyboardShouldPersistTaps={'always'}`set.  This resolved the problem for me.  Good luck!

**Closed** 2018-07-04 18:40 UTC

**Comment by samuelmataraso** [comment] 2019-02-24 21:42
the same problem here, + 1, I don't know what I need to do, for a single tap works to select an item of the list. I try with `keyboardShouldPersistTaps={"always"}` and nothing !

**Comment by rohanvasishth** [comment] 2022-08-05 10:03
Still facing this issue, I have used keyboardShouldPersistTaps={"always"} everywhere still not working.
