### ISSUE TITLE
How add custom value to textInput when press on cell

### ISSUE THREAD

**Issue by jose920405** [FaridSafi/react-native-google-places-autocomplete#80] opened 2016-12-13 16:49 UTC
It seems that the `getDefaultValue` only runs once and it does not help me when I put my custom state on that property.

I'm test too with `textInputProps` sending `onChangeText` function, but it's no good, because when the `_onPress` is executed it is forced to take the value of `rowData.description` and I lose control over that state. [code here](https://github.com/FaridSafi/react-native-google-places-autocomplete/blob/master/GooglePlacesAutocomplete.js#L276).

I would like to know if there is a way to achieve this and if it is not possible, then I would appreciate it being implemented for an upcoming version

**Comment by myaskevich** [comment] 2017-01-25 17:32
Hi @jose920405 

Did you try to call `onChangeText` right after `onPress` callback? It might help

**Comment by alan345** [comment] 2017-02-23 20:07
Hey, Thanks for your advise, but I ma not sure we can reach `onChangeText`
Example:
```
<GooglePlacesAutocomplete
          placeholder='hey!'
          minLength={2} // minimum length of text to search
          autoFocus={false}
          listViewDisplayed='auto'    // true/false/undefined
          fetchDetails={true}
          renderDescription={(row) => row.description} // custom description render
          onPress={(data, details = null) => { // 'details' is provided when fetchDetails = true
            // console.log(data);
            // console.log(details);
            this.onChangeText('');
```

of course `this.onChangeTex` is undefined..

Thanks for your help

**Comment by myaskevich** [comment] 2017-03-26 17:06
Hi @alan345 @jose920405 

Look like this is a duplicate of https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/84

Use `setAddressText` component method to take control over text input value.

**Closed by myaskevich** 2017-03-26 17:06 UTC

**Comment by spacewideweb** [comment] 2018-09-22 01:51
@mayask Can you write example how to use *setAddressText* component method?

**Comment by KamauIan** [comment] 2019-01-07 20:03
> @mayask Can you write example how to use `setAddressText` component method?

@spacewideweb we're you able to solve this?

**Comment by KamauIan** [comment] 2019-01-07 20:21
I found the solution: 

You can use setAddressText("...").

On your autocomplete component get a reference to the object:
<GooglePlacesAutocomplete ref={(instance) => { this.locationRef = instance }} .../>

and then:
this.locationRef.setAddressText("New York, NY")
[https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/158#issuecomment-372740996](url)
